#!/bin/sh

# Tomcat auto-start
#
# description: Auto-starts tomcat
# processname: tomcat
# pidfile: /var/run/tomcat.pid

case $1 in
start)
sudo -u tomcat sh /usr/local/tomcat/bin/startup.sh
;;
stop)
sudo -u tomcat sh /usr/local/tomcat/bin/shutdown.sh
;;
restart)
sudo -u tomcat sh /usr/local/tomcat/bin/shutdown.sh
sudo -u tomcat sh /usr/local/tomcat/bin/startup.sh
;;
esac
exit 0
